#First line indicated the Playlist version.
version=1
#Second line indicates background image.
background=previous
logo=none
title=Temptation Island Gallery
#
type=image
name=Groepsfoto 1
thumb=default
URL=http://www.temptation-island.nl/images/gallery/groep/TI6-Nelleke&Amina01.jpg
#
type=image
name=Groepsfoto 2
thumb=default
URL=http://www.temptation-island.nl/images/gallery/groep/TI6-Nelleke&Amina02.jpg
#
type=image
name=Groepsfoto 3
thumb=default
URL=http://www.temptation-island.nl/images/gallery/groep/TI6-Verleiders01.jpg
#
type=image
name=Groepsfoto 4
thumb=default
URL=http://www.temptation-island.nl/images/gallery/groep/TI6-Verleiders02.jpg
#
type=image
name=Groepsfoto 5
thumb=default
URL=http://www.temptation-island.nl/images/gallery/groep/TI6-Verleiders03.jpg
#
type=image
name=Groepsfoto 6
thumb=default
URL=http://www.temptation-island.nl/images/gallery/groep/TI6-VerleidersBelgie.jpg
#
type=image
name=Groepsfoto 7
thumb=default
URL=http://www.temptation-island.nl/images/gallery/groep/TI6-VerleidersNederland.jpg
#
type=image
name=Dorien
thumb=default
URL=http://www.temptation-island.nl/images/gallery/kandidaten/verleidsters/dorien/TI6-Dorien02.jpg
#
type=image
name=Amina
thumb=default
URL=http://www.temptation-island.nl/images/gallery/kandidaten/verleidsters/amina/TI6-Amina02.jpg
#
type=image
name=Bianca
thumb=default
URL=http://www.temptation-island.nl/images/gallery/kandidaten/verleidsters/singlebianca/TI6-Bianca02.jpg
#
type=image
name=Christina
thumb=default
URL=http://www.temptation-island.nl/images/gallery/kandidaten/verleidsters/christina/TI6-Christina01.jpg
#
type=image
name=Dave
thumb=default
URL=http://www.temptation-island.nl/images/gallery/kandidaten/verleiders/dave/TI6-Dave01.jpg
#
type=image
name=Dion
thumb=default
URL=http://www.temptation-island.nl/images/gallery/kandidaten/verleiders/dion/TI6-Dion02.jpg
#
type=image
name=Ellen
thumb=default
URL=http://www.temptation-island.nl/images/gallery/kandidaten/verleidsters/ellen/TI6-Ellen01.jpg
#
type=image
name=Filip
thumb=default
URL=http://www.temptation-island.nl/images/gallery/kandidaten/verleiders/filip/TI6-Filip01.jpg
#
type=image
name=Jeroen
thumb=default
URL=http://www.temptation-island.nl/images/gallery/kandidaten/verleiders/jeroen/TI6-Jeroen01.jpg
#
type=image
name=Kevin
thumb=default
URL=http://www.temptation-island.nl/images/gallery/kandidaten/verleiders/kevin/TI6-Kevin01.jpg
#
type=image
name=Laurent
thumb=default
URL=http://www.temptation-island.nl/images/gallery/kandidaten/verleiders/laurent/TI6-Laurent01.jpg
#
type=image
name=Melissa
thumb=default
URL=http://www.temptation-island.nl/images/gallery/kandidaten/verleidsters/melissa/TI6-Melissa01.jpg
#
type=image
name=Nelleke
thumb=default
URL=http://www.temptation-island.nl/images/gallery/kandidaten/verleidsters/nelleke/TI6-Nelleke01.jpg
#
type=image
name=Patricia
thumb=default
URL=http://www.temptation-island.nl/images/gallery/kandidaten/verleidsters/patricia/TI6-Patricia01.jpg
#
type=image
name=Roberto
thumb=default
URL=http://www.temptation-island.nl/images/gallery/kandidaten/verleiders/roberto/TI6-Roberto01.jpg
#
type=image
name=Woica
thumb=default
URL=http://www.temptation-island.nl/images/gallery/kandidaten/verleiders/wojca/TI6-Wojca01.jpg
#
type=image
name=Yoni
thumb=default
URL=http://www.temptation-island.nl/images/gallery/kandidaten/verleiders/yoni/TI6-Yoni01.jpg

